blank_issues_enabled: true
contact_links:
  - name: Телеграм чат maxo
    url: https://t.me/maxo_py
    about: Связь по всем вопросам
  - name: Макс чат maxo
    url: https://max.ru/join/rwJmWA4B5AipBiJdWRkORGjxFmqnJPUhJbQxxmscrnc
    about: Связь по всем вопросам
