"""
Методы MAX Bot API.

Тонкий реэкспорт `maxo.bot.methods` под именем `maxo.methods`.
Подражание aiogram, где методы лежат в `aiogram.methods`.
"""

from maxo.bot.methods import (
    AddMembers,
    AnswerOnCallback,
    DeleteAdmin,
    DeleteChat,
    DeleteMessage,
    EditBotInfo,
    EditChat,
    EditMessage,
    GetAdmins,
    GetChat,
    GetChatByLink,
    GetChats,
    GetMembers,
    GetMembership,
    GetMessageById,
    GetMessages,
    GetMyInfo,
    GetPinnedMessage,
    GetSubscriptions,
    GetUpdates,
    GetUploadUrl,
    GetVideoAttachmentDetails,
    LeaveChat,
    PinMessage,
    PostAdmins,
    RemoveMember,
    SendAction,
    SendMessage,
    SetAdmins,
    Subscribe,
    UnpinMessage,
    Unsubscribe,
    UploadMedia,
)

__all__ = (
    "AddMembers",
    "AnswerOnCallback",
    "DeleteAdmin",
    "DeleteChat",
    "DeleteMessage",
    "EditBotInfo",
    "EditChat",
    "EditMessage",
    "GetAdmins",
    "GetChat",
    "GetChatByLink",
    "GetChats",
    "GetMembers",
    "GetMembership",
    "GetMessageById",
    "GetMessages",
    "GetMyInfo",
    "GetPinnedMessage",
    "GetSubscriptions",
    "GetUpdates",
    "GetUploadUrl",
    "GetVideoAttachmentDetails",
    "LeaveChat",
    "PinMessage",
    "PostAdmins",
    "RemoveMember",
    "SendAction",
    "SendMessage",
    "SetAdmins",
    "Subscribe",
    "UnpinMessage",
    "Unsubscribe",
    "UploadMedia",
)
